# Generated by Django 6.0 on 2025-12-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laplog',
            name='map_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
