# Generated by Django 6.0 on 2025-12-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_laplog_map_polyline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laplog',
            name='map_polyline',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='map_polyline',
            field=models.TextField(blank=True, help_text='Encoded polyline string of the route', null=True),
        ),
    ]
