# Generated by Django 5.1.6 on 2025-11-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionblock',
            options={'ordering': ['block_order'], 'verbose_name': 'F_Session_Block', 'verbose_name_plural': 'F_Session_Block'},
        ),
        migrations.AlterModelTable(
            name='sessionblock',
            table='session_block',
        ),
    ]
