# Generated by Django 5.1.6 on 2025-11-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('focus', models.CharField(choices=[('Lift', 'Lift'), ('Cardio', 'Cardio'), ('Stretch', 'Stretch')], default='Lift', max_length=255)),
                ('day_of_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=255)),
                ('day_ordering', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'F_Session',
                'verbose_name_plural': 'F_Session',
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('muscle_groups', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/exercises/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('default_sets', models.IntegerField(default=3)),
                ('default_reps', models.IntegerField(default=8)),
                ('default_rest', models.IntegerField(default=60)),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'D_Exercise',
                'verbose_name_plural': 'D_Exercise',
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('focus', models.CharField(choices=[('Crossfit', 'Crossfit'), ('Yoga', 'Yoga'), ('Hybrid', 'Hybrid'), ('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Triathalon', 'Triathalon')], default='Strength', max_length=150)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/program/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'F_Program',
                'verbose_name_plural': 'F_Program',
                'db_table': 'program',
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProgramMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='img/program_media/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.program')),
            ],
            options={
                'verbose_name': 'F_Program Media',
                'verbose_name_plural': 'F_Program Media',
                'db_table': 'program_media',
            },
        ),
        migrations.CreateModel(
            name='SessionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_order', models.PositiveIntegerField(default=0)),
                ('scheme_type', models.CharField(choices=[('STANDARD', 'Standard List'), ('CIRCUIT', 'Circuit'), ('EMOM', 'Every Minute on the Minute'), ('AMRAP', 'As Many Rounds as Possible'), ('RFT', 'Rounds for Time'), ('TABATA', 'Tabata')], default='STANDARD', max_length=20)),
                ('duration_target', models.PositiveIntegerField(blank=True, help_text='Seconds for AMRAP/EMOM', null=True)),
                ('rounds_target', models.PositiveIntegerField(blank=True, help_text='Number of rounds for RFT', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.session')),
            ],
            options={
                'ordering': ['block_order'],
                'unique_together': {('session', 'block_order')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_in_block', models.IntegerField(default=0)),
                ('manual_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.exercise')),
                ('session_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.sessionblock')),
            ],
            options={
                'verbose_name': 'F_Activity',
                'verbose_name_plural': 'F_Activity',
                'db_table': 'activity',
                'unique_together': {('session_block', 'order_in_block')},
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('week_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.program')),
            ],
            options={
                'verbose_name': 'F_Week',
                'verbose_name_plural': 'F_Week',
                'db_table': 'week',
                'unique_together': {('program', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.week'),
        ),
        migrations.CreateModel(
            name='ActivityPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.PositiveIntegerField()),
                ('set_tag', models.CharField(choices=[('N', 'Normal / Working Set'), ('W', 'Warmup'), ('D', 'Drop Set'), ('F', 'Failure / AMRAP'), ('C', 'Cool Down')], default='N', max_length=1)),
                ('primary_metric', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time'), ('distance', 'Distance'), ('calories', 'Calories'), ('weight', 'Weight'), ('none', 'None')], default='reps', max_length=20)),
                ('prescription_notes', models.TextField(blank=True, null=True)),
                ('reps', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('tempo', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, help_text='Always stored in kg', max_digits=12, null=True)),
                ('is_per_side', models.BooleanField(default=False)),
                ('intensity_value', models.CharField(blank=True, max_length=50, null=True)),
                ('intensity_type', models.CharField(blank=True, choices=[('weight', 'Weight'), ('rpe', 'RPE'), ('power', 'Power'), ('perc_ftp', '%FTP'), ('percent_1rm', '%1RM'), ('heart_rate_zone', 'HR Zone'), ('heart_rate', 'Heart Rate'), ('pace', 'Pace'), ('calories', 'Calories')], max_length=50, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=4, help_text='Always stored in meters. Frontend converts to miles/km/yards.', max_digits=12, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.activity')),
            ],
            options={
                'verbose_name': 'F_Activity_Prescription',
                'verbose_name_plural': 'F_Activity_Prescription',
                'db_table': 'activity_prescription',
                'unique_together': {('activity', 'set_number')},
            },
        ),
    ]
