# Generated by Django 5.1.6 on 2025-11-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sessionblock_options_alter_sessionblock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/equipment/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'D_Equipment',
                'verbose_name_plural': 'D_Equipment',
                'db_table': 'equipment',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order_in_block'], 'verbose_name': 'F_Activity', 'verbose_name_plural': 'F_Activity'},
        ),
        migrations.AlterModelOptions(
            name='programmedia',
            options={'verbose_name': 'F_Program_Media', 'verbose_name_plural': 'F_Program_Media'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['week_number'], 'verbose_name': 'F_Week', 'verbose_name_plural': 'F_Week'},
        ),
        migrations.AddField(
            model_name='activity',
            name='manual_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/manual_activites/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='manual_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityprescription',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Target calories for Row/Ski/Bike', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/session/'),
        ),
        migrations.AddField(
            model_name='sessionblock',
            name='block_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionblock',
            name='block_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityprescription',
            name='intensity_type',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('rpe', 'RPE'), ('power', 'Power'), ('perc_ftp', '%FTP'), ('percent_1rm', '%1RM'), ('heart_rate_zone', 'HR Zone'), ('heart_rate', 'Heart Rate'), ('pace', 'Pace')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activityprescription',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionblock',
            name='scheme_type',
            field=models.CharField(choices=[('STANDARD', 'Standard List'), ('CIRCUIT', 'Circuit'), ('INTERVAL', 'Interval'), ('EMOM', 'Every Minute on the Minute'), ('AMRAP', 'As Many Rounds as Possible'), ('RFT', 'Rounds for Time'), ('TABATA', 'Tabata')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='ProgramEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_equipment', to='core.equipment')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_equipment', to='core.program')),
            ],
            options={
                'verbose_name': 'F_Program_Equipment',
                'verbose_name_plural': 'F_Program_Equipment',
                'db_table': 'program_equipment',
            },
        ),
    ]
