# Generated by Django 6.0 on 2025-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityprescription',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='activityprescription',
            name='primary_metric',
        ),
        migrations.AlterField(
            model_name='activityprescription',
            name='intensity_type',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('rpe', 'RPE'), ('power', 'Power'), ('perc_ftp', '%FTP'), ('percent_1rm', '%1RM'), ('heart_rate_zone', 'HR Zone'), ('heart_rate', 'Heart Rate'), ('pace', 'Pace'), ('watts', 'Watts')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sessionblock',
            name='scheme_type',
            field=models.CharField(choices=[('STANDARD', 'Standard List'), ('EMOM', 'Every Minute on the Minute'), ('AMRAP', 'As Many Rounds as Possible'), ('RFT', 'Rounds for Time')], default='STANDARD', max_length=20),
        ),
    ]
